/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\track-striped-wide-corner-large.glb -c -t
*/

import * as THREE from 'three'
import {useGLTF} from '@react-three/drei'
import {GLTF} from 'three-stdlib'
import {RigidBody} from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    ['track-striped-wide-corner-large_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
}

export function TrackStripedWideCornerLargeModel(props: JSX.IntrinsicElements['group']) {
  const {nodes, materials} = useGLTF('/models/toy_card_kit/track-striped-wide-corner-large.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes['track-striped-wide-corner-large_1'].geometry}
          material={materials.colormap}
          position={[0, 0, 0]}
        />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/models/toy_card_kit/track-striped-wide-corner-large.glb')
